import React, { useState } from "react";
import { 
  Sparkles, 
  X, 
  Send, 
  Bot, 
  User, 
  CheckSquare, 
  ArrowRight, 
  Plus, 
  Clock, 
  Calendar, 
  AlertCircle,
  Lightbulb
} from "lucide-react";
import { Task, Project, Goal, Note, WorkspaceType } from "../types";

interface ActionBotDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  tasks: Task[];
  projects: Project[];
  goals: Goal[];
  notes: Note[];
  activeWorkspace: WorkspaceType;
  onAddTask: (task: Omit<Task, "id" | "createdAt">) => void;
}

interface Message {
  id: string;
  sender: "user" | "bot";
  text: string;
  suggestedTasks?: { title: string; priority: string; workspace: string }[];
}

export const ActionBotDrawer: React.FC<ActionBotDrawerProps> = ({
  isOpen,
  onClose,
  tasks,
  projects,
  goals,
  notes,
  activeWorkspace,
  onAddTask
}) => {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      sender: "bot",
      text: "Greetings. I am ActionBot, your cross-workspace intelligence copilot. I analyze your deadlines, tasks, and notes to eliminate cognitive friction. How can I assist your focus today?"
    }
  ]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  if (!isOpen) return null;

  const handleSend = async (userPrompt: string) => {
    const text = userPrompt.trim();
    if (!text || isLoading) return;

    const userMsg: Message = {
      id: Date.now().toString(),
      sender: "user",
      text
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsLoading(true);

    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: text,
          context: {
            activeWorkspace,
            tasksSummary: tasks.map((t) => `[${t.workspace}] ${t.title} (${t.priority}) - ${t.completed ? "DONE" : "PENDING"}`),
            goalsSummary: goals.map((g) => `[${g.workspace}] ${g.title}: ${g.progress}%`),
            recentNotes: notes.slice(0, 3).map((n) => `${n.title}: ${n.content.slice(0, 100)}`)
          }
        })
      });

      const data = await res.json();
      const botResponseText: string = data.response || "I have analyzed your workspace context.";

      // Check if response contains [ADD_TASK] directives
      const suggested: { title: string; priority: string; workspace: string }[] = [];
      const lines = botResponseText.split("\n");
      lines.forEach((line) => {
        if (line.includes("[ADD_TASK]")) {
          const taskContent = line.replace("[ADD_TASK]", "").trim();
          suggested.push({
            title: taskContent,
            priority: "HIGH",
            workspace: activeWorkspace
          });
        }
      });

      setMessages((prev) => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          sender: "bot",
          text: botResponseText.replace(/\[ADD_TASK\].*$/gm, "").trim(),
          suggestedTasks: suggested.length > 0 ? suggested : undefined
        }
      ]);
    } catch {
      // Local fallback
      setMessages((prev) => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          sender: "bot",
          text: `Here is your current priority plan for ${activeWorkspace}:\n1. Tackle the most urgent deadline.\n2. Dedicate a 50-minute Pomodoro sprint with 432Hz soundscape.\n3. Clear pending subtasks before end of day.`
        }
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleAddSuggestedTask = (task: { title: string; priority: string; workspace: string }) => {
    onAddTask({
      title: task.title,
      description: "Generated by ActionBot Copilot",
      deadline: "Today",
      dueDate: new Date().toISOString().slice(0, 10),
      priority: task.priority as any || "HIGH",
      workspace: task.workspace || activeWorkspace,
      category: "ActionBot",
      tags: ["ai", "actionbot"],
      subtasks: [],
      attachments: [],
      recurring: "none",
      status: "pending"
    });
  };

  return (
    <div className="fixed inset-y-0 right-0 z-50 w-full sm:w-[440px] bg-surface border-l border-border-hairline apple-shadow-dark flex flex-col animate-in slide-in-from-right duration-200">
      
      {/* Drawer Header */}
      <div className="p-5 border-b border-border-hairline flex items-center justify-between bg-surface-muted/60">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-primary/10 text-primary flex items-center justify-center">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="font-bold text-sm text-text-primary">ActionBot Copilot</h3>
            <p className="text-[11px] font-mono text-emerald-600">Cross-Workspace Intelligence</p>
          </div>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="w-7 h-7 rounded-full hover:bg-surface-container flex items-center justify-center text-text-secondary cursor-pointer"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Suggested Quick Prompt Pills */}
      <div className="p-3 border-b border-border-hairline bg-surface flex items-center gap-1.5 overflow-x-auto text-[11px] font-mono">
        <button
          type="button"
          onClick={() => handleSend("Plan my day based on current pending tasks and deadlines.")}
          className="px-2.5 py-1 rounded-full bg-surface-muted hover:bg-surface-container border border-border-hairline text-text-secondary hover:text-text-primary whitespace-nowrap cursor-pointer"
        >
          📅 Plan My Day
        </button>
        <button
          type="button"
          onClick={() => handleSend("What tasks are currently high risk or urgent?")}
          className="px-2.5 py-1 rounded-full bg-surface-muted hover:bg-surface-container border border-border-hairline text-text-secondary hover:text-text-primary whitespace-nowrap cursor-pointer"
        >
          ⚠️ Check Risks
        </button>
        <button
          type="button"
          onClick={() => handleSend("Suggest a 3-step focus roadmap for today.")}
          className="px-2.5 py-1 rounded-full bg-surface-muted hover:bg-surface-container border border-border-hairline text-text-secondary hover:text-text-primary whitespace-nowrap cursor-pointer"
        >
          🎯 Focus Roadmap
        </button>
      </div>

      {/* Messages Stream */}
      <div className="p-5 overflow-y-auto space-y-4 flex-1">
        {messages.map((m) => (
          <div
            key={m.id}
            className={`flex gap-3 text-xs ${
              m.sender === "user" ? "flex-row-reverse" : "flex-row"
            }`}
          >
            <div
              className={`w-7 h-7 rounded-xl flex items-center justify-center shrink-0 ${
                m.sender === "user"
                  ? "bg-text-primary text-white"
                  : "bg-primary/10 text-primary"
              }`}
            >
              {m.sender === "user" ? <User className="w-3.5 h-3.5" /> : <Bot className="w-3.5 h-3.5" />}
            </div>

            <div
              className={`p-4 rounded-2xl max-w-[85%] space-y-2 leading-relaxed whitespace-pre-wrap ${
                m.sender === "user"
                  ? "bg-primary text-white font-medium"
                  : "bg-surface-muted border border-border-hairline text-text-primary font-sans"
              }`}
            >
              <div>{m.text}</div>

              {/* Actionable task pills injected by bot */}
              {m.suggestedTasks && (
                <div className="pt-2 border-t border-border-hairline space-y-1.5">
                  <div className="text-[10px] font-mono text-primary uppercase font-bold">
                    Suggested Tasks
                  </div>
                  {m.suggestedTasks.map((st, idx) => (
                    <button
                      key={idx}
                      type="button"
                      onClick={() => handleAddSuggestedTask(st)}
                      className="w-full p-2 rounded-xl bg-surface hover:bg-surface-container border border-border-hairline text-left flex items-center justify-between text-xs cursor-pointer transition-colors"
                    >
                      <span className="font-semibold text-text-primary truncate">{st.title}</span>
                      <Plus className="w-3.5 h-3.5 text-primary shrink-0 ml-2" />
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}

        {isLoading && (
          <div className="flex items-center gap-2 text-xs font-mono text-text-tertiary p-2">
            <span className="w-2 h-2 rounded-full bg-primary animate-ping"></span>
            <span>ActionBot is synthesizing workspace intelligence...</span>
          </div>
        )}
      </div>

      {/* Input Box */}
      <div className="p-4 border-t border-border-hairline bg-surface">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSend(input);
          }}
          className="flex items-center gap-2"
        >
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask ActionBot anything about your tasks..."
            className="flex-1 px-4 py-2.5 rounded-2xl bg-surface-muted border border-border-hairline text-xs text-text-primary focus:outline-none focus:ring-1 focus:ring-primary"
          />
          <button
            type="submit"
            disabled={!input.trim() || isLoading}
            className="apple-btn p-2.5 rounded-2xl bg-primary hover:bg-primary-hover disabled:opacity-40 text-white cursor-pointer transition-colors"
          >
            <Send className="w-4 h-4" />
          </button>
        </form>
      </div>

    </div>
  );
};
